### ISSUE TITLE
腿哥，是吗？

### ISSUE THREAD

**Issue by SchopenhauerZhang** [imsiren/mt_util#2]
你是腿哥本人吗？你博客imsiren.com打不开了。

**Comment by imsiren** [comment]
嗯，数据丢失，停了。

**Comment by SchopenhauerZhang** [comment]
那腿哥，怎么联系你啊？最近想你了：）

**Comment by imsiren** [comment]
你是？？

**Comment by SchopenhauerZhang** [comment]
我18年在mt搬砖，后来您走了，一直没机会向腿哥请教。
和商业化团队有些许接触，当时有个基于mt_util的小项目交给我了，没搞明白我也走了.(:-
